# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2
from src.protobuf import tiles_pb2 as tiles__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animation.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61nimation.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\x1a\x0btiles.proto\"\xc8\x03\n\x0eStartAnimation\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12*\n\x0b\x66irst_frame\x18\x02 \x01(\x0b\x32\x15.CARTA.AnimationFrame\x12*\n\x0bstart_frame\x18\x03 \x01(\x0b\x32\x15.CARTA.AnimationFrame\x12)\n\nlast_frame\x18\x04 \x01(\x0b\x32\x15.CARTA.AnimationFrame\x12*\n\x0b\x64\x65lta_frame\x18\x05 \x01(\x0b\x32\x15.CARTA.AnimationFrame\x12\x12\n\nframe_rate\x18\x06 \x01(\x0f\x12\x0f\n\x07looping\x18\x07 \x01(\x08\x12\x0f\n\x07reverse\x18\x08 \x01(\x08\x12/\n\x0erequired_tiles\x18\t \x01(\x0b\x32\x17.CARTA.AddRequiredTiles\x12@\n\x0ematched_frames\x18\n \x03(\x0b\x32(.CARTA.StartAnimation.MatchedFramesEntry\x1aM\n\x12MatchedFramesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0f\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.CARTA.MatchedFrameList:\x02\x38\x01\"K\n\x11StartAnimationAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61nimation_id\x18\x03 \x01(\x0f\"\x7f\n\x14\x41nimationFlowControl\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12-\n\x0ereceived_frame\x18\x02 \x01(\x0b\x32\x15.CARTA.AnimationFrame\x12\x14\n\x0c\x61nimation_id\x18\x03 \x01(\x0f\x12\x11\n\ttimestamp\x18\x04 \x01(\x10\"J\n\rStopAnimation\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12(\n\tend_frame\x18\x02 \x01(\x0b\x32\x15.CARTA.AnimationFrameb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,tiles__pb2.DESCRIPTOR,])




_STARTANIMATION_MATCHEDFRAMESENTRY = _descriptor.Descriptor(
  name='MatchedFramesEntry',
  full_name='CARTA.StartAnimation.MatchedFramesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.StartAnimation.MatchedFramesEntry.key', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.StartAnimation.MatchedFramesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=508,
)

_STARTANIMATION = _descriptor.Descriptor(
  name='StartAnimation',
  full_name='CARTA.StartAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.StartAnimation.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_frame', full_name='CARTA.StartAnimation.first_frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_frame', full_name='CARTA.StartAnimation.start_frame', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_frame', full_name='CARTA.StartAnimation.last_frame', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delta_frame', full_name='CARTA.StartAnimation.delta_frame', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_rate', full_name='CARTA.StartAnimation.frame_rate', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='looping', full_name='CARTA.StartAnimation.looping', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reverse', full_name='CARTA.StartAnimation.reverse', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='required_tiles', full_name='CARTA.StartAnimation.required_tiles', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matched_frames', full_name='CARTA.StartAnimation.matched_frames', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STARTANIMATION_MATCHEDFRAMESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=508,
)


_STARTANIMATIONACK = _descriptor.Descriptor(
  name='StartAnimationAck',
  full_name='CARTA.StartAnimationAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.StartAnimationAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.StartAnimationAck.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='CARTA.StartAnimationAck.animation_id', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=585,
)


_ANIMATIONFLOWCONTROL = _descriptor.Descriptor(
  name='AnimationFlowControl',
  full_name='CARTA.AnimationFlowControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.AnimationFlowControl.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='received_frame', full_name='CARTA.AnimationFlowControl.received_frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='CARTA.AnimationFlowControl.animation_id', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CARTA.AnimationFlowControl.timestamp', index=3,
      number=4, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=714,
)


_STOPANIMATION = _descriptor.Descriptor(
  name='StopAnimation',
  full_name='CARTA.StopAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.StopAnimation.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_frame', full_name='CARTA.StopAnimation.end_frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=790,
)

_STARTANIMATION_MATCHEDFRAMESENTRY.fields_by_name['value'].message_type = defs__pb2._MATCHEDFRAMELIST
_STARTANIMATION_MATCHEDFRAMESENTRY.containing_type = _STARTANIMATION
_STARTANIMATION.fields_by_name['first_frame'].message_type = defs__pb2._ANIMATIONFRAME
_STARTANIMATION.fields_by_name['start_frame'].message_type = defs__pb2._ANIMATIONFRAME
_STARTANIMATION.fields_by_name['last_frame'].message_type = defs__pb2._ANIMATIONFRAME
_STARTANIMATION.fields_by_name['delta_frame'].message_type = defs__pb2._ANIMATIONFRAME
_STARTANIMATION.fields_by_name['required_tiles'].message_type = tiles__pb2._ADDREQUIREDTILES
_STARTANIMATION.fields_by_name['matched_frames'].message_type = _STARTANIMATION_MATCHEDFRAMESENTRY
_ANIMATIONFLOWCONTROL.fields_by_name['received_frame'].message_type = defs__pb2._ANIMATIONFRAME
_STOPANIMATION.fields_by_name['end_frame'].message_type = defs__pb2._ANIMATIONFRAME
DESCRIPTOR.message_types_by_name['StartAnimation'] = _STARTANIMATION
DESCRIPTOR.message_types_by_name['StartAnimationAck'] = _STARTANIMATIONACK
DESCRIPTOR.message_types_by_name['AnimationFlowControl'] = _ANIMATIONFLOWCONTROL
DESCRIPTOR.message_types_by_name['StopAnimation'] = _STOPANIMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartAnimation = _reflection.GeneratedProtocolMessageType('StartAnimation', (_message.Message,), {

  'MatchedFramesEntry' : _reflection.GeneratedProtocolMessageType('MatchedFramesEntry', (_message.Message,), {
    'DESCRIPTOR' : _STARTANIMATION_MATCHEDFRAMESENTRY,
    '__module__' : 'animation_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.StartAnimation.MatchedFramesEntry)
    })
  ,
  'DESCRIPTOR' : _STARTANIMATION,
  '__module__' : 'animation_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.StartAnimation)
  })
_sym_db.RegisterMessage(StartAnimation)
_sym_db.RegisterMessage(StartAnimation.MatchedFramesEntry)

StartAnimationAck = _reflection.GeneratedProtocolMessageType('StartAnimationAck', (_message.Message,), {
  'DESCRIPTOR' : _STARTANIMATIONACK,
  '__module__' : 'animation_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.StartAnimationAck)
  })
_sym_db.RegisterMessage(StartAnimationAck)

AnimationFlowControl = _reflection.GeneratedProtocolMessageType('AnimationFlowControl', (_message.Message,), {
  'DESCRIPTOR' : _ANIMATIONFLOWCONTROL,
  '__module__' : 'animation_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.AnimationFlowControl)
  })
_sym_db.RegisterMessage(AnimationFlowControl)

StopAnimation = _reflection.GeneratedProtocolMessageType('StopAnimation', (_message.Message,), {
  'DESCRIPTOR' : _STOPANIMATION,
  '__module__' : 'animation_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.StopAnimation)
  })
_sym_db.RegisterMessage(StopAnimation)


_STARTANIMATION_MATCHEDFRAMESENTRY._options = None
# @@protoc_insertion_point(module_scope)
