# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog_filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import enums_pb2 as enums__pb2
from src.protobuf import defs_pb2 as defs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='catalog_filter.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61talog_filter.proto\x12\x05\x43\x41RTA\x1a\x0b\x65nums.proto\x1a\ndefs.proto\"\xbc\x02\n\x14\x43\x61talogFilterRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x16\n\x0e\x63olumn_indices\x18\x02 \x03(\x05\x12+\n\x0e\x66ilter_configs\x18\x03 \x03(\x0b\x32\x13.CARTA.FilterConfig\x12\x18\n\x10subset_data_size\x18\x04 \x01(\x0f\x12\x1a\n\x12subset_start_index\x18\x05 \x01(\x0f\x12/\n\x0cimage_bounds\x18\x06 \x01(\x0b\x32\x19.CARTA.CatalogImageBounds\x12\x15\n\rimage_file_id\x18\x07 \x01(\x0f\x12\x11\n\tregion_id\x18\x08 \x01(\x0f\x12\x13\n\x0bsort_column\x18\t \x01(\t\x12(\n\x0csorting_type\x18\n \x01(\x0e\x32\x12.CARTA.SortingType\"\xcc\x02\n\x15\x43\x61talogFilterResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x15\n\rimage_file_id\x18\x02 \x01(\x0f\x12\x11\n\tregion_id\x18\x03 \x01(\x0f\x12:\n\x07\x63olumns\x18\x04 \x03(\x0b\x32).CARTA.CatalogFilterResponse.ColumnsEntry\x12\x18\n\x10subset_data_size\x18\x05 \x01(\x0f\x12\x18\n\x10subset_end_index\x18\x06 \x01(\x0f\x12\x10\n\x08progress\x18\x07 \x01(\x02\x12\x18\n\x10\x66ilter_data_size\x18\x08 \x01(\x0f\x12\x19\n\x11request_end_index\x18\t \x01(\x0f\x1a\x41\n\x0c\x43olumnsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x07\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.CARTA.ColumnData:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,defs__pb2.DESCRIPTOR,])




_CATALOGFILTERREQUEST = _descriptor.Descriptor(
  name='CatalogFilterRequest',
  full_name='CARTA.CatalogFilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.CatalogFilterRequest.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_indices', full_name='CARTA.CatalogFilterRequest.column_indices', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_configs', full_name='CARTA.CatalogFilterRequest.filter_configs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subset_data_size', full_name='CARTA.CatalogFilterRequest.subset_data_size', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subset_start_index', full_name='CARTA.CatalogFilterRequest.subset_start_index', index=4,
      number=5, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_bounds', full_name='CARTA.CatalogFilterRequest.image_bounds', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_file_id', full_name='CARTA.CatalogFilterRequest.image_file_id', index=6,
      number=7, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.CatalogFilterRequest.region_id', index=7,
      number=8, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sort_column', full_name='CARTA.CatalogFilterRequest.sort_column', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sorting_type', full_name='CARTA.CatalogFilterRequest.sorting_type', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=373,
)


_CATALOGFILTERRESPONSE_COLUMNSENTRY = _descriptor.Descriptor(
  name='ColumnsEntry',
  full_name='CARTA.CatalogFilterResponse.ColumnsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.CatalogFilterResponse.ColumnsEntry.key', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.CatalogFilterResponse.ColumnsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=708,
)

_CATALOGFILTERRESPONSE = _descriptor.Descriptor(
  name='CatalogFilterResponse',
  full_name='CARTA.CatalogFilterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.CatalogFilterResponse.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_file_id', full_name='CARTA.CatalogFilterResponse.image_file_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.CatalogFilterResponse.region_id', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='CARTA.CatalogFilterResponse.columns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subset_data_size', full_name='CARTA.CatalogFilterResponse.subset_data_size', index=4,
      number=5, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subset_end_index', full_name='CARTA.CatalogFilterResponse.subset_end_index', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='CARTA.CatalogFilterResponse.progress', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_data_size', full_name='CARTA.CatalogFilterResponse.filter_data_size', index=7,
      number=8, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_end_index', full_name='CARTA.CatalogFilterResponse.request_end_index', index=8,
      number=9, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CATALOGFILTERRESPONSE_COLUMNSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=708,
)

_CATALOGFILTERREQUEST.fields_by_name['filter_configs'].message_type = defs__pb2._FILTERCONFIG
_CATALOGFILTERREQUEST.fields_by_name['image_bounds'].message_type = defs__pb2._CATALOGIMAGEBOUNDS
_CATALOGFILTERREQUEST.fields_by_name['sorting_type'].enum_type = enums__pb2._SORTINGTYPE
_CATALOGFILTERRESPONSE_COLUMNSENTRY.fields_by_name['value'].message_type = defs__pb2._COLUMNDATA
_CATALOGFILTERRESPONSE_COLUMNSENTRY.containing_type = _CATALOGFILTERRESPONSE
_CATALOGFILTERRESPONSE.fields_by_name['columns'].message_type = _CATALOGFILTERRESPONSE_COLUMNSENTRY
DESCRIPTOR.message_types_by_name['CatalogFilterRequest'] = _CATALOGFILTERREQUEST
DESCRIPTOR.message_types_by_name['CatalogFilterResponse'] = _CATALOGFILTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CatalogFilterRequest = _reflection.GeneratedProtocolMessageType('CatalogFilterRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGFILTERREQUEST,
  '__module__' : 'catalog_filter_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.CatalogFilterRequest)
  })
_sym_db.RegisterMessage(CatalogFilterRequest)

CatalogFilterResponse = _reflection.GeneratedProtocolMessageType('CatalogFilterResponse', (_message.Message,), {

  'ColumnsEntry' : _reflection.GeneratedProtocolMessageType('ColumnsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATALOGFILTERRESPONSE_COLUMNSENTRY,
    '__module__' : 'catalog_filter_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.CatalogFilterResponse.ColumnsEntry)
    })
  ,
  'DESCRIPTOR' : _CATALOGFILTERRESPONSE,
  '__module__' : 'catalog_filter_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.CatalogFilterResponse)
  })
_sym_db.RegisterMessage(CatalogFilterResponse)
_sym_db.RegisterMessage(CatalogFilterResponse.ColumnsEntry)


_CATALOGFILTERRESPONSE_COLUMNSENTRY._options = None
# @@protoc_insertion_point(module_scope)
