# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='catalog_list.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63\x61talog_list.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\"\'\n\x12\x43\x61talogListRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"\x99\x01\n\x13\x43\x61talogListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tdirectory\x18\x03 \x01(\t\x12\x0e\n\x06parent\x18\x04 \x01(\t\x12%\n\x05\x66iles\x18\x05 \x03(\x0b\x32\x16.CARTA.CatalogFileInfo\x12\x16\n\x0esubdirectories\x18\x06 \x03(\tb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,])




_CATALOGLISTREQUEST = _descriptor.Descriptor(
  name='CatalogListRequest',
  full_name='CARTA.CatalogListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='directory', full_name='CARTA.CatalogListRequest.directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=80,
)


_CATALOGLISTRESPONSE = _descriptor.Descriptor(
  name='CatalogListResponse',
  full_name='CARTA.CatalogListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.CatalogListResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.CatalogListResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='directory', full_name='CARTA.CatalogListResponse.directory', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent', full_name='CARTA.CatalogListResponse.parent', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='files', full_name='CARTA.CatalogListResponse.files', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subdirectories', full_name='CARTA.CatalogListResponse.subdirectories', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=236,
)

_CATALOGLISTRESPONSE.fields_by_name['files'].message_type = defs__pb2._CATALOGFILEINFO
DESCRIPTOR.message_types_by_name['CatalogListRequest'] = _CATALOGLISTREQUEST
DESCRIPTOR.message_types_by_name['CatalogListResponse'] = _CATALOGLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CatalogListRequest = _reflection.GeneratedProtocolMessageType('CatalogListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGLISTREQUEST,
  '__module__' : 'catalog_list_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.CatalogListRequest)
  })
_sym_db.RegisterMessage(CatalogListRequest)

CatalogListResponse = _reflection.GeneratedProtocolMessageType('CatalogListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGLISTRESPONSE,
  '__module__' : 'catalog_list_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.CatalogListResponse)
  })
_sym_db.RegisterMessage(CatalogListResponse)


# @@protoc_insertion_point(module_scope)
