# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: export_region.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2
from src.protobuf import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='export_region.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x65xport_region.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\x1a\x0b\x65nums.proto\"\x91\x02\n\x0c\x45xportRegion\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.CARTA.FileType\x12)\n\ncoord_type\x18\x02 \x01(\x0e\x32\x15.CARTA.CoordinateType\x12\x0f\n\x07\x66ile_id\x18\x03 \x01(\x0f\x12<\n\rregion_styles\x18\x04 \x03(\x0b\x32%.CARTA.ExportRegion.RegionStylesEntry\x12\x11\n\tdirectory\x18\x05 \x01(\t\x12\x0c\n\x04\x66ile\x18\x06 \x01(\t\x1aG\n\x11RegionStylesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0f\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.CARTA.RegionStyle:\x02\x38\x01\"E\n\x0f\x45xportRegionAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x03(\tb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,enums__pb2.DESCRIPTOR,])




_EXPORTREGION_REGIONSTYLESENTRY = _descriptor.Descriptor(
  name='RegionStylesEntry',
  full_name='CARTA.ExportRegion.RegionStylesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.ExportRegion.RegionStylesEntry.key', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.ExportRegion.RegionStylesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=329,
)

_EXPORTREGION = _descriptor.Descriptor(
  name='ExportRegion',
  full_name='CARTA.ExportRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CARTA.ExportRegion.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coord_type', full_name='CARTA.ExportRegion.coord_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.ExportRegion.file_id', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_styles', full_name='CARTA.ExportRegion.region_styles', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='directory', full_name='CARTA.ExportRegion.directory', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='CARTA.ExportRegion.file', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXPORTREGION_REGIONSTYLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=329,
)


_EXPORTREGIONACK = _descriptor.Descriptor(
  name='ExportRegionAck',
  full_name='CARTA.ExportRegionAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.ExportRegionAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.ExportRegionAck.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contents', full_name='CARTA.ExportRegionAck.contents', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=400,
)

_EXPORTREGION_REGIONSTYLESENTRY.fields_by_name['value'].message_type = defs__pb2._REGIONSTYLE
_EXPORTREGION_REGIONSTYLESENTRY.containing_type = _EXPORTREGION
_EXPORTREGION.fields_by_name['type'].enum_type = enums__pb2._FILETYPE
_EXPORTREGION.fields_by_name['coord_type'].enum_type = enums__pb2._COORDINATETYPE
_EXPORTREGION.fields_by_name['region_styles'].message_type = _EXPORTREGION_REGIONSTYLESENTRY
DESCRIPTOR.message_types_by_name['ExportRegion'] = _EXPORTREGION
DESCRIPTOR.message_types_by_name['ExportRegionAck'] = _EXPORTREGIONACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExportRegion = _reflection.GeneratedProtocolMessageType('ExportRegion', (_message.Message,), {

  'RegionStylesEntry' : _reflection.GeneratedProtocolMessageType('RegionStylesEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXPORTREGION_REGIONSTYLESENTRY,
    '__module__' : 'export_region_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.ExportRegion.RegionStylesEntry)
    })
  ,
  'DESCRIPTOR' : _EXPORTREGION,
  '__module__' : 'export_region_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ExportRegion)
  })
_sym_db.RegisterMessage(ExportRegion)
_sym_db.RegisterMessage(ExportRegion.RegionStylesEntry)

ExportRegionAck = _reflection.GeneratedProtocolMessageType('ExportRegionAck', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTREGIONACK,
  '__module__' : 'export_region_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ExportRegionAck)
  })
_sym_db.RegisterMessage(ExportRegionAck)


_EXPORTREGION_REGIONSTYLESENTRY._options = None
# @@protoc_insertion_point(module_scope)
