# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_info.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66ile_info.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\"?\n\x0f\x46ileInfoRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0b\n\x03hdu\x18\x03 \x01(\t\"\x8d\x01\n\x10\x46ileInfoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\tfile_info\x18\x03 \x01(\x0b\x32\x0f.CARTA.FileInfo\x12\x33\n\x12\x66ile_info_extended\x18\x04 \x01(\x0b\x32\x17.CARTA.FileInfoExtendedb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,])




_FILEINFOREQUEST = _descriptor.Descriptor(
  name='FileInfoRequest',
  full_name='CARTA.FileInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='directory', full_name='CARTA.FileInfoRequest.directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='CARTA.FileInfoRequest.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hdu', full_name='CARTA.FileInfoRequest.hdu', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=101,
)


_FILEINFORESPONSE = _descriptor.Descriptor(
  name='FileInfoResponse',
  full_name='CARTA.FileInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.FileInfoResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.FileInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_info', full_name='CARTA.FileInfoResponse.file_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_info_extended', full_name='CARTA.FileInfoResponse.file_info_extended', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=245,
)

_FILEINFORESPONSE.fields_by_name['file_info'].message_type = defs__pb2._FILEINFO
_FILEINFORESPONSE.fields_by_name['file_info_extended'].message_type = defs__pb2._FILEINFOEXTENDED
DESCRIPTOR.message_types_by_name['FileInfoRequest'] = _FILEINFOREQUEST
DESCRIPTOR.message_types_by_name['FileInfoResponse'] = _FILEINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileInfoRequest = _reflection.GeneratedProtocolMessageType('FileInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFOREQUEST,
  '__module__' : 'file_info_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.FileInfoRequest)
  })
_sym_db.RegisterMessage(FileInfoRequest)

FileInfoResponse = _reflection.GeneratedProtocolMessageType('FileInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFORESPONSE,
  '__module__' : 'file_info_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.FileInfoResponse)
  })
_sym_db.RegisterMessage(FileInfoResponse)


# @@protoc_insertion_point(module_scope)
