# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moment_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2
from src.protobuf import enums_pb2 as enums__pb2
from src.protobuf import open_file_pb2 as open__file__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='moment_request.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14moment_request.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\x1a\x0b\x65nums.proto\x1a\x0fopen_file.proto\"\xe8\x01\n\rMomentRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x1e\n\x07moments\x18\x02 \x03(\x0e\x32\r.CARTA.Moment\x12\x1f\n\x04\x61xis\x18\x03 \x01(\x0e\x32\x11.CARTA.MomentAxis\x12\x11\n\tregion_id\x18\x04 \x01(\x0f\x12(\n\x0espectral_range\x18\x05 \x01(\x0b\x32\x10.CARTA.IntBounds\x12\x1f\n\x04mask\x18\x06 \x01(\x0e\x32\x11.CARTA.MomentMask\x12\'\n\x0bpixel_range\x18\x07 \x01(\x0b\x32\x12.CARTA.FloatBounds\"^\n\x0eMomentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x0eopen_file_acks\x18\x03 \x03(\x0b\x32\x12.CARTA.OpenFileAck\"3\n\x0eMomentProgress\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x10\n\x08progress\x18\x02 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,enums__pb2.DESCRIPTOR,open__file__pb2.DESCRIPTOR,])




_MOMENTREQUEST = _descriptor.Descriptor(
  name='MomentRequest',
  full_name='CARTA.MomentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.MomentRequest.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='moments', full_name='CARTA.MomentRequest.moments', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axis', full_name='CARTA.MomentRequest.axis', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.MomentRequest.region_id', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectral_range', full_name='CARTA.MomentRequest.spectral_range', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='CARTA.MomentRequest.mask', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixel_range', full_name='CARTA.MomentRequest.pixel_range', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=306,
)


_MOMENTRESPONSE = _descriptor.Descriptor(
  name='MomentResponse',
  full_name='CARTA.MomentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.MomentResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.MomentResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open_file_acks', full_name='CARTA.MomentResponse.open_file_acks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=402,
)


_MOMENTPROGRESS = _descriptor.Descriptor(
  name='MomentProgress',
  full_name='CARTA.MomentProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.MomentProgress.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='CARTA.MomentProgress.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=455,
)

_MOMENTREQUEST.fields_by_name['moments'].enum_type = enums__pb2._MOMENT
_MOMENTREQUEST.fields_by_name['axis'].enum_type = enums__pb2._MOMENTAXIS
_MOMENTREQUEST.fields_by_name['spectral_range'].message_type = defs__pb2._INTBOUNDS
_MOMENTREQUEST.fields_by_name['mask'].enum_type = enums__pb2._MOMENTMASK
_MOMENTREQUEST.fields_by_name['pixel_range'].message_type = defs__pb2._FLOATBOUNDS
_MOMENTRESPONSE.fields_by_name['open_file_acks'].message_type = open__file__pb2._OPENFILEACK
DESCRIPTOR.message_types_by_name['MomentRequest'] = _MOMENTREQUEST
DESCRIPTOR.message_types_by_name['MomentResponse'] = _MOMENTRESPONSE
DESCRIPTOR.message_types_by_name['MomentProgress'] = _MOMENTPROGRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MomentRequest = _reflection.GeneratedProtocolMessageType('MomentRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOMENTREQUEST,
  '__module__' : 'moment_request_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.MomentRequest)
  })
_sym_db.RegisterMessage(MomentRequest)

MomentResponse = _reflection.GeneratedProtocolMessageType('MomentResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOMENTRESPONSE,
  '__module__' : 'moment_request_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.MomentResponse)
  })
_sym_db.RegisterMessage(MomentResponse)

MomentProgress = _reflection.GeneratedProtocolMessageType('MomentProgress', (_message.Message,), {
  'DESCRIPTOR' : _MOMENTPROGRESS,
  '__module__' : 'moment_request_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.MomentProgress)
  })
_sym_db.RegisterMessage(MomentProgress)


# @@protoc_insertion_point(module_scope)
