# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raster_tile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raster_tile.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11raster_tile.proto\x12\x05\x43\x41RTA\x1a\x0b\x65nums.proto\"j\n\x0eRasterTileSync\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x0f\x12\x0e\n\x06stokes\x18\x03 \x01(\x0f\x12\x14\n\x0c\x61nimation_id\x18\x04 \x01(\x0f\x12\x10\n\x08\x65nd_sync\x18\x05 \x01(\x08\"\xc7\x01\n\x0eRasterTileData\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x0f\x12\x0e\n\x06stokes\x18\x03 \x01(\x0f\x12\x30\n\x10\x63ompression_type\x18\x04 \x01(\x0e\x32\x16.CARTA.CompressionType\x12\x1b\n\x13\x63ompression_quality\x18\x05 \x01(\x02\x12\x14\n\x0c\x61nimation_id\x18\x06 \x01(\x0f\x12\x1e\n\x05tiles\x18\x07 \x03(\x0b\x32\x0f.CARTA.TileData\"y\n\x08TileData\x12\r\n\x05layer\x18\x01 \x01(\x0f\x12\t\n\x01x\x18\x02 \x01(\x0f\x12\t\n\x01y\x18\x03 \x01(\x0f\x12\r\n\x05width\x18\x04 \x01(\x0f\x12\x0e\n\x06height\x18\x05 \x01(\x0f\x12\x12\n\nimage_data\x18\x06 \x01(\x0c\x12\x15\n\rnan_encodings\x18\x07 \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])




_RASTERTILESYNC = _descriptor.Descriptor(
  name='RasterTileSync',
  full_name='CARTA.RasterTileSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.RasterTileSync.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CARTA.RasterTileSync.channel', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stokes', full_name='CARTA.RasterTileSync.stokes', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='CARTA.RasterTileSync.animation_id', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_sync', full_name='CARTA.RasterTileSync.end_sync', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=147,
)


_RASTERTILEDATA = _descriptor.Descriptor(
  name='RasterTileData',
  full_name='CARTA.RasterTileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.RasterTileData.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CARTA.RasterTileData.channel', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stokes', full_name='CARTA.RasterTileData.stokes', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compression_type', full_name='CARTA.RasterTileData.compression_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compression_quality', full_name='CARTA.RasterTileData.compression_quality', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='CARTA.RasterTileData.animation_id', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='CARTA.RasterTileData.tiles', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=349,
)


_TILEDATA = _descriptor.Descriptor(
  name='TileData',
  full_name='CARTA.TileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer', full_name='CARTA.TileData.layer', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='CARTA.TileData.x', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='CARTA.TileData.y', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='CARTA.TileData.width', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='CARTA.TileData.height', index=4,
      number=5, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='CARTA.TileData.image_data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nan_encodings', full_name='CARTA.TileData.nan_encodings', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=472,
)

_RASTERTILEDATA.fields_by_name['compression_type'].enum_type = enums__pb2._COMPRESSIONTYPE
_RASTERTILEDATA.fields_by_name['tiles'].message_type = _TILEDATA
DESCRIPTOR.message_types_by_name['RasterTileSync'] = _RASTERTILESYNC
DESCRIPTOR.message_types_by_name['RasterTileData'] = _RASTERTILEDATA
DESCRIPTOR.message_types_by_name['TileData'] = _TILEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RasterTileSync = _reflection.GeneratedProtocolMessageType('RasterTileSync', (_message.Message,), {
  'DESCRIPTOR' : _RASTERTILESYNC,
  '__module__' : 'raster_tile_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.RasterTileSync)
  })
_sym_db.RegisterMessage(RasterTileSync)

RasterTileData = _reflection.GeneratedProtocolMessageType('RasterTileData', (_message.Message,), {
  'DESCRIPTOR' : _RASTERTILEDATA,
  '__module__' : 'raster_tile_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.RasterTileData)
  })
_sym_db.RegisterMessage(RasterTileData)

TileData = _reflection.GeneratedProtocolMessageType('TileData', (_message.Message,), {
  'DESCRIPTOR' : _TILEDATA,
  '__module__' : 'raster_tile_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.TileData)
  })
_sym_db.RegisterMessage(TileData)


# @@protoc_insertion_point(module_scope)
