# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: region_requirements.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='region_requirements.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19region_requirements.proto\x12\x05\x43\x41RTA\x1a\x0b\x65nums.proto\"[\n\x14SetStatsRequirements\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x11\n\tregion_id\x18\x02 \x01(\x0f\x12\x1f\n\x05stats\x18\x03 \x03(\x0e\x32\x10.CARTA.StatsType\"\xb9\x01\n\x18SetHistogramRequirements\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x11\n\tregion_id\x18\x02 \x01(\x0f\x12\x43\n\nhistograms\x18\x03 \x03(\x0b\x32/.CARTA.SetHistogramRequirements.HistogramConfig\x1a\x34\n\x0fHistogramConfig\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x0f\x12\x10\n\x08num_bins\x18\x02 \x01(\x0f\"V\n\x16SetSpatialRequirements\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x11\n\tregion_id\x18\x02 \x01(\x0f\x12\x18\n\x10spatial_profiles\x18\x03 \x03(\t\"\xd4\x01\n\x17SetSpectralRequirements\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x11\n\tregion_id\x18\x02 \x01(\x0f\x12H\n\x11spectral_profiles\x18\x03 \x03(\x0b\x32-.CARTA.SetSpectralRequirements.SpectralConfig\x1aK\n\x0eSpectralConfig\x12\x12\n\ncoordinate\x18\x01 \x01(\t\x12%\n\x0bstats_types\x18\x02 \x03(\x0e\x32\x10.CARTA.StatsType\"y\n\x15SetRegionRequirements\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x07\x12\x11\n\tregion_id\x18\x02 \x01(\x07\x12\t\n\x01x\x18\x03 \x01(\x08\x12\t\n\x01y\x18\x04 \x01(\x08\x12\t\n\x01z\x18\x05 \x01(\x08\x12\x1b\n\x13\x61\x64\x64itional_profiles\x18\x06 \x03(\tb\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])




_SETSTATSREQUIREMENTS = _descriptor.Descriptor(
  name='SetStatsRequirements',
  full_name='CARTA.SetStatsRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SetStatsRequirements.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SetStatsRequirements.region_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stats', full_name='CARTA.SetStatsRequirements.stats', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=140,
)


_SETHISTOGRAMREQUIREMENTS_HISTOGRAMCONFIG = _descriptor.Descriptor(
  name='HistogramConfig',
  full_name='CARTA.SetHistogramRequirements.HistogramConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='CARTA.SetHistogramRequirements.HistogramConfig.channel', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_bins', full_name='CARTA.SetHistogramRequirements.HistogramConfig.num_bins', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=328,
)

_SETHISTOGRAMREQUIREMENTS = _descriptor.Descriptor(
  name='SetHistogramRequirements',
  full_name='CARTA.SetHistogramRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SetHistogramRequirements.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SetHistogramRequirements.region_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='histograms', full_name='CARTA.SetHistogramRequirements.histograms', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SETHISTOGRAMREQUIREMENTS_HISTOGRAMCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=328,
)


_SETSPATIALREQUIREMENTS = _descriptor.Descriptor(
  name='SetSpatialRequirements',
  full_name='CARTA.SetSpatialRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SetSpatialRequirements.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SetSpatialRequirements.region_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spatial_profiles', full_name='CARTA.SetSpatialRequirements.spatial_profiles', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=416,
)


_SETSPECTRALREQUIREMENTS_SPECTRALCONFIG = _descriptor.Descriptor(
  name='SpectralConfig',
  full_name='CARTA.SetSpectralRequirements.SpectralConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='CARTA.SetSpectralRequirements.SpectralConfig.coordinate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stats_types', full_name='CARTA.SetSpectralRequirements.SpectralConfig.stats_types', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=631,
)

_SETSPECTRALREQUIREMENTS = _descriptor.Descriptor(
  name='SetSpectralRequirements',
  full_name='CARTA.SetSpectralRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SetSpectralRequirements.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SetSpectralRequirements.region_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectral_profiles', full_name='CARTA.SetSpectralRequirements.spectral_profiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SETSPECTRALREQUIREMENTS_SPECTRALCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=631,
)


_SETREGIONREQUIREMENTS = _descriptor.Descriptor(
  name='SetRegionRequirements',
  full_name='CARTA.SetRegionRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SetRegionRequirements.file_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SetRegionRequirements.region_id', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='CARTA.SetRegionRequirements.x', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='CARTA.SetRegionRequirements.y', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='CARTA.SetRegionRequirements.z', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additional_profiles', full_name='CARTA.SetRegionRequirements.additional_profiles', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=754,
)

_SETSTATSREQUIREMENTS.fields_by_name['stats'].enum_type = enums__pb2._STATSTYPE
_SETHISTOGRAMREQUIREMENTS_HISTOGRAMCONFIG.containing_type = _SETHISTOGRAMREQUIREMENTS
_SETHISTOGRAMREQUIREMENTS.fields_by_name['histograms'].message_type = _SETHISTOGRAMREQUIREMENTS_HISTOGRAMCONFIG
_SETSPECTRALREQUIREMENTS_SPECTRALCONFIG.fields_by_name['stats_types'].enum_type = enums__pb2._STATSTYPE
_SETSPECTRALREQUIREMENTS_SPECTRALCONFIG.containing_type = _SETSPECTRALREQUIREMENTS
_SETSPECTRALREQUIREMENTS.fields_by_name['spectral_profiles'].message_type = _SETSPECTRALREQUIREMENTS_SPECTRALCONFIG
DESCRIPTOR.message_types_by_name['SetStatsRequirements'] = _SETSTATSREQUIREMENTS
DESCRIPTOR.message_types_by_name['SetHistogramRequirements'] = _SETHISTOGRAMREQUIREMENTS
DESCRIPTOR.message_types_by_name['SetSpatialRequirements'] = _SETSPATIALREQUIREMENTS
DESCRIPTOR.message_types_by_name['SetSpectralRequirements'] = _SETSPECTRALREQUIREMENTS
DESCRIPTOR.message_types_by_name['SetRegionRequirements'] = _SETREGIONREQUIREMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetStatsRequirements = _reflection.GeneratedProtocolMessageType('SetStatsRequirements', (_message.Message,), {
  'DESCRIPTOR' : _SETSTATSREQUIREMENTS,
  '__module__' : 'region_requirements_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetStatsRequirements)
  })
_sym_db.RegisterMessage(SetStatsRequirements)

SetHistogramRequirements = _reflection.GeneratedProtocolMessageType('SetHistogramRequirements', (_message.Message,), {

  'HistogramConfig' : _reflection.GeneratedProtocolMessageType('HistogramConfig', (_message.Message,), {
    'DESCRIPTOR' : _SETHISTOGRAMREQUIREMENTS_HISTOGRAMCONFIG,
    '__module__' : 'region_requirements_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.SetHistogramRequirements.HistogramConfig)
    })
  ,
  'DESCRIPTOR' : _SETHISTOGRAMREQUIREMENTS,
  '__module__' : 'region_requirements_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetHistogramRequirements)
  })
_sym_db.RegisterMessage(SetHistogramRequirements)
_sym_db.RegisterMessage(SetHistogramRequirements.HistogramConfig)

SetSpatialRequirements = _reflection.GeneratedProtocolMessageType('SetSpatialRequirements', (_message.Message,), {
  'DESCRIPTOR' : _SETSPATIALREQUIREMENTS,
  '__module__' : 'region_requirements_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetSpatialRequirements)
  })
_sym_db.RegisterMessage(SetSpatialRequirements)

SetSpectralRequirements = _reflection.GeneratedProtocolMessageType('SetSpectralRequirements', (_message.Message,), {

  'SpectralConfig' : _reflection.GeneratedProtocolMessageType('SpectralConfig', (_message.Message,), {
    'DESCRIPTOR' : _SETSPECTRALREQUIREMENTS_SPECTRALCONFIG,
    '__module__' : 'region_requirements_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.SetSpectralRequirements.SpectralConfig)
    })
  ,
  'DESCRIPTOR' : _SETSPECTRALREQUIREMENTS,
  '__module__' : 'region_requirements_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetSpectralRequirements)
  })
_sym_db.RegisterMessage(SetSpectralRequirements)
_sym_db.RegisterMessage(SetSpectralRequirements.SpectralConfig)

SetRegionRequirements = _reflection.GeneratedProtocolMessageType('SetRegionRequirements', (_message.Message,), {
  'DESCRIPTOR' : _SETREGIONREQUIREMENTS,
  '__module__' : 'region_requirements_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetRegionRequirements)
  })
_sym_db.RegisterMessage(SetRegionRequirements)


# @@protoc_insertion_point(module_scope)
