# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resume_session.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2
from src.protobuf import enums_pb2 as enums__pb2
from src.protobuf import open_catalog_file_pb2 as open__catalog__file__pb2
from src.protobuf import contour_pb2 as contour__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resume_session.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14resume_session.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\x1a\x0b\x65nums.proto\x1a\x17open_catalog_file.proto\x1a\rcontour.proto\"\xc9\x02\n\x0fImageProperties\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0b\n\x03hdu\x18\x03 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x04 \x01(\x0f\x12&\n\x0brender_mode\x18\x05 \x01(\x0e\x32\x11.CARTA.RenderMode\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\x0f\x12\x0e\n\x06stokes\x18\x07 \x01(\x0f\x12\x34\n\x07regions\x18\x08 \x03(\x0b\x32#.CARTA.ImageProperties.RegionsEntry\x12\x35\n\x10\x63ontour_settings\x18\t \x01(\x0b\x32\x1b.CARTA.SetContourParameters\x1a\x41\n\x0cRegionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0f\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.CARTA.RegionInfo:\x02\x38\x01\"f\n\rResumeSession\x12&\n\x06images\x18\x01 \x03(\x0b\x32\x16.CARTA.ImageProperties\x12-\n\rcatalog_files\x18\x02 \x03(\x0b\x32\x16.CARTA.OpenCatalogFile\"4\n\x10ResumeSessionAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,enums__pb2.DESCRIPTOR,open__catalog__file__pb2.DESCRIPTOR,contour__pb2.DESCRIPTOR,])




_IMAGEPROPERTIES_REGIONSENTRY = _descriptor.Descriptor(
  name='RegionsEntry',
  full_name='CARTA.ImageProperties.RegionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.ImageProperties.RegionsEntry.key', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.ImageProperties.RegionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=426,
)

_IMAGEPROPERTIES = _descriptor.Descriptor(
  name='ImageProperties',
  full_name='CARTA.ImageProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='directory', full_name='CARTA.ImageProperties.directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='CARTA.ImageProperties.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hdu', full_name='CARTA.ImageProperties.hdu', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.ImageProperties.file_id', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='render_mode', full_name='CARTA.ImageProperties.render_mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CARTA.ImageProperties.channel', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stokes', full_name='CARTA.ImageProperties.stokes', index=6,
      number=7, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regions', full_name='CARTA.ImageProperties.regions', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contour_settings', full_name='CARTA.ImageProperties.contour_settings', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEPROPERTIES_REGIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=426,
)


_RESUMESESSION = _descriptor.Descriptor(
  name='ResumeSession',
  full_name='CARTA.ResumeSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='CARTA.ResumeSession.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='catalog_files', full_name='CARTA.ResumeSession.catalog_files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=530,
)


_RESUMESESSIONACK = _descriptor.Descriptor(
  name='ResumeSessionAck',
  full_name='CARTA.ResumeSessionAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.ResumeSessionAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.ResumeSessionAck.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=584,
)

_IMAGEPROPERTIES_REGIONSENTRY.fields_by_name['value'].message_type = defs__pb2._REGIONINFO
_IMAGEPROPERTIES_REGIONSENTRY.containing_type = _IMAGEPROPERTIES
_IMAGEPROPERTIES.fields_by_name['render_mode'].enum_type = enums__pb2._RENDERMODE
_IMAGEPROPERTIES.fields_by_name['regions'].message_type = _IMAGEPROPERTIES_REGIONSENTRY
_IMAGEPROPERTIES.fields_by_name['contour_settings'].message_type = contour__pb2._SETCONTOURPARAMETERS
_RESUMESESSION.fields_by_name['images'].message_type = _IMAGEPROPERTIES
_RESUMESESSION.fields_by_name['catalog_files'].message_type = open__catalog__file__pb2._OPENCATALOGFILE
DESCRIPTOR.message_types_by_name['ImageProperties'] = _IMAGEPROPERTIES
DESCRIPTOR.message_types_by_name['ResumeSession'] = _RESUMESESSION
DESCRIPTOR.message_types_by_name['ResumeSessionAck'] = _RESUMESESSIONACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageProperties = _reflection.GeneratedProtocolMessageType('ImageProperties', (_message.Message,), {

  'RegionsEntry' : _reflection.GeneratedProtocolMessageType('RegionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _IMAGEPROPERTIES_REGIONSENTRY,
    '__module__' : 'resume_session_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.ImageProperties.RegionsEntry)
    })
  ,
  'DESCRIPTOR' : _IMAGEPROPERTIES,
  '__module__' : 'resume_session_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ImageProperties)
  })
_sym_db.RegisterMessage(ImageProperties)
_sym_db.RegisterMessage(ImageProperties.RegionsEntry)

ResumeSession = _reflection.GeneratedProtocolMessageType('ResumeSession', (_message.Message,), {
  'DESCRIPTOR' : _RESUMESESSION,
  '__module__' : 'resume_session_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ResumeSession)
  })
_sym_db.RegisterMessage(ResumeSession)

ResumeSessionAck = _reflection.GeneratedProtocolMessageType('ResumeSessionAck', (_message.Message,), {
  'DESCRIPTOR' : _RESUMESESSIONACK,
  '__module__' : 'resume_session_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ResumeSessionAck)
  })
_sym_db.RegisterMessage(ResumeSessionAck)


_IMAGEPROPERTIES_REGIONSENTRY._options = None
# @@protoc_insertion_point(module_scope)
