# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spatial_profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import defs_pb2 as defs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spatial_profile.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15spatial_profile.proto\x12\x05\x43\x41RTA\x1a\ndefs.proto\"\xa7\x01\n\x12SpatialProfileData\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\x11\n\tregion_id\x18\x02 \x01(\x0f\x12\t\n\x01x\x18\x03 \x01(\x0f\x12\t\n\x01y\x18\x04 \x01(\x0f\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\x0f\x12\x0e\n\x06stokes\x18\x06 \x01(\x0f\x12\r\n\x05value\x18\x07 \x01(\x02\x12\'\n\x08profiles\x18\x08 \x03(\x0b\x32\x15.CARTA.SpatialProfileb\x06proto3'
  ,
  dependencies=[defs__pb2.DESCRIPTOR,])




_SPATIALPROFILEDATA = _descriptor.Descriptor(
  name='SpatialProfileData',
  full_name='CARTA.SpatialProfileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.SpatialProfileData.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='CARTA.SpatialProfileData.region_id', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='CARTA.SpatialProfileData.x', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='CARTA.SpatialProfileData.y', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CARTA.SpatialProfileData.channel', index=4,
      number=5, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stokes', full_name='CARTA.SpatialProfileData.stokes', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.SpatialProfileData.value', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profiles', full_name='CARTA.SpatialProfileData.profiles', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=212,
)

_SPATIALPROFILEDATA.fields_by_name['profiles'].message_type = defs__pb2._SPATIALPROFILE
DESCRIPTOR.message_types_by_name['SpatialProfileData'] = _SPATIALPROFILEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpatialProfileData = _reflection.GeneratedProtocolMessageType('SpatialProfileData', (_message.Message,), {
  'DESCRIPTOR' : _SPATIALPROFILEDATA,
  '__module__' : 'spatial_profile_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SpatialProfileData)
  })
_sym_db.RegisterMessage(SpatialProfileData)


# @@protoc_insertion_point(module_scope)
