# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tiles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protobuf import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tiles.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btiles.proto\x12\x05\x43\x41RTA\x1a\x0b\x65nums.proto\"\x81\x01\n\x10\x41\x64\x64RequiredTiles\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\r\n\x05tiles\x18\x02 \x03(\x0f\x12\x30\n\x10\x63ompression_type\x18\x03 \x01(\x0e\x32\x16.CARTA.CompressionType\x12\x1b\n\x13\x63ompression_quality\x18\x04 \x01(\x02\"5\n\x13RemoveRequiredTiles\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x12\r\n\x05tiles\x18\x02 \x03(\x0f\x62\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])




_ADDREQUIREDTILES = _descriptor.Descriptor(
  name='AddRequiredTiles',
  full_name='CARTA.AddRequiredTiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.AddRequiredTiles.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='CARTA.AddRequiredTiles.tiles', index=1,
      number=2, type=15, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compression_type', full_name='CARTA.AddRequiredTiles.compression_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compression_quality', full_name='CARTA.AddRequiredTiles.compression_quality', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=165,
)


_REMOVEREQUIREDTILES = _descriptor.Descriptor(
  name='RemoveRequiredTiles',
  full_name='CARTA.RemoveRequiredTiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.RemoveRequiredTiles.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='CARTA.RemoveRequiredTiles.tiles', index=1,
      number=2, type=15, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=220,
)

_ADDREQUIREDTILES.fields_by_name['compression_type'].enum_type = enums__pb2._COMPRESSIONTYPE
DESCRIPTOR.message_types_by_name['AddRequiredTiles'] = _ADDREQUIREDTILES
DESCRIPTOR.message_types_by_name['RemoveRequiredTiles'] = _REMOVEREQUIREDTILES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequiredTiles = _reflection.GeneratedProtocolMessageType('AddRequiredTiles', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUIREDTILES,
  '__module__' : 'tiles_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.AddRequiredTiles)
  })
_sym_db.RegisterMessage(AddRequiredTiles)

RemoveRequiredTiles = _reflection.GeneratedProtocolMessageType('RemoveRequiredTiles', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEREQUIREDTILES,
  '__module__' : 'tiles_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.RemoveRequiredTiles)
  })
_sym_db.RegisterMessage(RemoveRequiredTiles)


# @@protoc_insertion_point(module_scope)
