# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: close_file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='close_file.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63lose_file.proto\x12\x05\x43\x41RTA\"\x1c\n\tCloseFile\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x0f\x62\x06proto3'
)




_CLOSEFILE = _descriptor.Descriptor(
  name='CloseFile',
  full_name='CARTA.CloseFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='CARTA.CloseFile.file_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['CloseFile'] = _CLOSEFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloseFile = _reflection.GeneratedProtocolMessageType('CloseFile', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEFILE,
  '__module__' : 'close_file_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.CloseFile)
  })
_sym_db.RegisterMessage(CloseFile)


# @@protoc_insertion_point(module_scope)
