# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register_viewer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='register_viewer.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15register_viewer.proto\x12\x05\x43\x41RTA\x1a\x0b\x65nums.proto\"S\n\x0eRegisterViewer\x12\x12\n\nsession_id\x18\x01 \x01(\x07\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x1c\n\x14\x63lient_feature_flags\x18\x03 \x01(\x07\"\x87\x03\n\x11RegisterViewerAck\x12\x12\n\nsession_id\x18\x01 \x01(\x07\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12(\n\x0csession_type\x18\x04 \x01(\x0e\x32\x12.CARTA.SessionType\x12\x1c\n\x14server_feature_flags\x18\x05 \x01(\x07\x12G\n\x10user_preferences\x18\x06 \x03(\x0b\x32-.CARTA.RegisterViewerAck.UserPreferencesEntry\x12?\n\x0cuser_layouts\x18\x07 \x03(\x0b\x32).CARTA.RegisterViewerAck.UserLayoutsEntry\x1a\x36\n\x14UserPreferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10UserLayoutsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])




_REGISTERVIEWER = _descriptor.Descriptor(
  name='RegisterViewer',
  full_name='CARTA.RegisterViewer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CARTA.RegisterViewer.session_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_key', full_name='CARTA.RegisterViewer.api_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_feature_flags', full_name='CARTA.RegisterViewer.client_feature_flags', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=128,
)


_REGISTERVIEWERACK_USERPREFERENCESENTRY = _descriptor.Descriptor(
  name='UserPreferencesEntry',
  full_name='CARTA.RegisterViewerAck.UserPreferencesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.RegisterViewerAck.UserPreferencesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.RegisterViewerAck.UserPreferencesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=470,
)

_REGISTERVIEWERACK_USERLAYOUTSENTRY = _descriptor.Descriptor(
  name='UserLayoutsEntry',
  full_name='CARTA.RegisterViewerAck.UserLayoutsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.RegisterViewerAck.UserLayoutsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.RegisterViewerAck.UserLayoutsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=522,
)

_REGISTERVIEWERACK = _descriptor.Descriptor(
  name='RegisterViewerAck',
  full_name='CARTA.RegisterViewerAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CARTA.RegisterViewerAck.session_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.RegisterViewerAck.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.RegisterViewerAck.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_type', full_name='CARTA.RegisterViewerAck.session_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_feature_flags', full_name='CARTA.RegisterViewerAck.server_feature_flags', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_preferences', full_name='CARTA.RegisterViewerAck.user_preferences', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_layouts', full_name='CARTA.RegisterViewerAck.user_layouts', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERVIEWERACK_USERPREFERENCESENTRY, _REGISTERVIEWERACK_USERLAYOUTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=522,
)

_REGISTERVIEWERACK_USERPREFERENCESENTRY.containing_type = _REGISTERVIEWERACK
_REGISTERVIEWERACK_USERLAYOUTSENTRY.containing_type = _REGISTERVIEWERACK
_REGISTERVIEWERACK.fields_by_name['session_type'].enum_type = enums__pb2._SESSIONTYPE
_REGISTERVIEWERACK.fields_by_name['user_preferences'].message_type = _REGISTERVIEWERACK_USERPREFERENCESENTRY
_REGISTERVIEWERACK.fields_by_name['user_layouts'].message_type = _REGISTERVIEWERACK_USERLAYOUTSENTRY
DESCRIPTOR.message_types_by_name['RegisterViewer'] = _REGISTERVIEWER
DESCRIPTOR.message_types_by_name['RegisterViewerAck'] = _REGISTERVIEWERACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterViewer = _reflection.GeneratedProtocolMessageType('RegisterViewer', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERVIEWER,
  '__module__' : 'register_viewer_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.RegisterViewer)
  })
_sym_db.RegisterMessage(RegisterViewer)

RegisterViewerAck = _reflection.GeneratedProtocolMessageType('RegisterViewerAck', (_message.Message,), {

  'UserPreferencesEntry' : _reflection.GeneratedProtocolMessageType('UserPreferencesEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERVIEWERACK_USERPREFERENCESENTRY,
    '__module__' : 'register_viewer_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.RegisterViewerAck.UserPreferencesEntry)
    })
  ,

  'UserLayoutsEntry' : _reflection.GeneratedProtocolMessageType('UserLayoutsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERVIEWERACK_USERLAYOUTSENTRY,
    '__module__' : 'register_viewer_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.RegisterViewerAck.UserLayoutsEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTERVIEWERACK,
  '__module__' : 'register_viewer_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.RegisterViewerAck)
  })
_sym_db.RegisterMessage(RegisterViewerAck)
_sym_db.RegisterMessage(RegisterViewerAck.UserPreferencesEntry)
_sym_db.RegisterMessage(RegisterViewerAck.UserLayoutsEntry)


_REGISTERVIEWERACK_USERPREFERENCESENTRY._options = None
_REGISTERVIEWERACK_USERLAYOUTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
