# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scripting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scripting.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fscripting.proto\x12\x05\x43\x41RTA\"s\n\x10ScriptingRequest\x12\x1c\n\x14scripting_request_id\x18\x01 \x01(\x0f\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\t\x12\r\n\x05\x61sync\x18\x05 \x01(\x08\"e\n\x11ScriptingResponse\x12\x1c\n\x14scripting_request_id\x18\x01 \x01(\x0f\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08response\x18\x04 \x01(\tb\x06proto3'
)




_SCRIPTINGREQUEST = _descriptor.Descriptor(
  name='ScriptingRequest',
  full_name='CARTA.ScriptingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scripting_request_id', full_name='CARTA.ScriptingRequest.scripting_request_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='CARTA.ScriptingRequest.target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='CARTA.ScriptingRequest.action', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='CARTA.ScriptingRequest.parameters', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='async', full_name='CARTA.ScriptingRequest.async', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=141,
)


_SCRIPTINGRESPONSE = _descriptor.Descriptor(
  name='ScriptingResponse',
  full_name='CARTA.ScriptingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scripting_request_id', full_name='CARTA.ScriptingResponse.scripting_request_id', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.ScriptingResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CARTA.ScriptingResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='CARTA.ScriptingResponse.response', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['ScriptingRequest'] = _SCRIPTINGREQUEST
DESCRIPTOR.message_types_by_name['ScriptingResponse'] = _SCRIPTINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScriptingRequest = _reflection.GeneratedProtocolMessageType('ScriptingRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTINGREQUEST,
  '__module__' : 'scripting_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ScriptingRequest)
  })
_sym_db.RegisterMessage(ScriptingRequest)

ScriptingResponse = _reflection.GeneratedProtocolMessageType('ScriptingResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTINGRESPONSE,
  '__module__' : 'scripting_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.ScriptingResponse)
  })
_sym_db.RegisterMessage(ScriptingResponse)


# @@protoc_insertion_point(module_scope)
