# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_preferences.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_preferences.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16user_preferences.proto\x12\x05\x43\x41RTA\"\x90\x01\n\x12SetUserPreferences\x12\x44\n\x0epreference_map\x18\x01 \x03(\x0b\x32,.CARTA.SetUserPreferences.PreferenceMapEntry\x1a\x34\n\x12PreferenceMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"(\n\x15SetUserPreferencesAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3'
)




_SETUSERPREFERENCES_PREFERENCEMAPENTRY = _descriptor.Descriptor(
  name='PreferenceMapEntry',
  full_name='CARTA.SetUserPreferences.PreferenceMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CARTA.SetUserPreferences.PreferenceMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.SetUserPreferences.PreferenceMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=178,
)

_SETUSERPREFERENCES = _descriptor.Descriptor(
  name='SetUserPreferences',
  full_name='CARTA.SetUserPreferences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='preference_map', full_name='CARTA.SetUserPreferences.preference_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SETUSERPREFERENCES_PREFERENCEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=178,
)


_SETUSERPREFERENCESACK = _descriptor.Descriptor(
  name='SetUserPreferencesAck',
  full_name='CARTA.SetUserPreferencesAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.SetUserPreferencesAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=220,
)

_SETUSERPREFERENCES_PREFERENCEMAPENTRY.containing_type = _SETUSERPREFERENCES
_SETUSERPREFERENCES.fields_by_name['preference_map'].message_type = _SETUSERPREFERENCES_PREFERENCEMAPENTRY
DESCRIPTOR.message_types_by_name['SetUserPreferences'] = _SETUSERPREFERENCES
DESCRIPTOR.message_types_by_name['SetUserPreferencesAck'] = _SETUSERPREFERENCESACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetUserPreferences = _reflection.GeneratedProtocolMessageType('SetUserPreferences', (_message.Message,), {

  'PreferenceMapEntry' : _reflection.GeneratedProtocolMessageType('PreferenceMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SETUSERPREFERENCES_PREFERENCEMAPENTRY,
    '__module__' : 'user_preferences_pb2'
    # @@protoc_insertion_point(class_scope:CARTA.SetUserPreferences.PreferenceMapEntry)
    })
  ,
  'DESCRIPTOR' : _SETUSERPREFERENCES,
  '__module__' : 'user_preferences_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetUserPreferences)
  })
_sym_db.RegisterMessage(SetUserPreferences)
_sym_db.RegisterMessage(SetUserPreferences.PreferenceMapEntry)

SetUserPreferencesAck = _reflection.GeneratedProtocolMessageType('SetUserPreferencesAck', (_message.Message,), {
  'DESCRIPTOR' : _SETUSERPREFERENCESACK,
  '__module__' : 'user_preferences_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetUserPreferencesAck)
  })
_sym_db.RegisterMessage(SetUserPreferencesAck)


_SETUSERPREFERENCES_PREFERENCEMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
