# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_layout.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_layout.proto',
  package='CARTA',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11user_layout.proto\x12\x05\x43\x41RTA\",\n\rSetUserLayout\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"#\n\x10SetUserLayoutAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3'
)




_SETUSERLAYOUT = _descriptor.Descriptor(
  name='SetUserLayout',
  full_name='CARTA.SetUserLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CARTA.SetUserLayout.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CARTA.SetUserLayout.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=72,
)


_SETUSERLAYOUTACK = _descriptor.Descriptor(
  name='SetUserLayoutAck',
  full_name='CARTA.SetUserLayoutAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CARTA.SetUserLayoutAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['SetUserLayout'] = _SETUSERLAYOUT
DESCRIPTOR.message_types_by_name['SetUserLayoutAck'] = _SETUSERLAYOUTACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetUserLayout = _reflection.GeneratedProtocolMessageType('SetUserLayout', (_message.Message,), {
  'DESCRIPTOR' : _SETUSERLAYOUT,
  '__module__' : 'user_layout_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetUserLayout)
  })
_sym_db.RegisterMessage(SetUserLayout)

SetUserLayoutAck = _reflection.GeneratedProtocolMessageType('SetUserLayoutAck', (_message.Message,), {
  'DESCRIPTOR' : _SETUSERLAYOUTACK,
  '__module__' : 'user_layout_pb2'
  # @@protoc_insertion_point(class_scope:CARTA.SetUserLayoutAck)
  })
_sym_db.RegisterMessage(SetUserLayoutAck)


# @@protoc_insertion_point(module_scope)
